'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="master")>  _
Partial Public Class DataClassesDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("masterConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property EmployeeL10s() As System.Data.Linq.Table(Of EmployeeL10)
		Get
			Return Me.GetTable(Of EmployeeL10)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.EmployeeL10")>  _
Partial Public Class EmployeeL10
	
	Private _Employee_ID As String
	
	Private _Employee_Name As String
	
	Private _L10 As String
	
	Private _Email_Alias As String
	
	Private _Job_Title As String
	
	Private _Country_Name As String
	
	Private _Manager_Name As String
	
	Private _Manager_Employee_ID As String
	
	Private _Manager_Email_Alias As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Employee ID]", Storage:="_Employee_ID", DbType:="VarChar(50)")>  _
	Public Property Employee_ID() As String
		Get
			Return Me._Employee_ID
		End Get
		Set
			If (String.Equals(Me._Employee_ID, value) = false) Then
				Me._Employee_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Employee Name]", Storage:="_Employee_Name", DbType:="VarChar(50)")>  _
	Public Property Employee_Name() As String
		Get
			Return Me._Employee_Name
		End Get
		Set
			If (String.Equals(Me._Employee_Name, value) = false) Then
				Me._Employee_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_L10", DbType:="VarChar(50)")>  _
	Public Property L10() As String
		Get
			Return Me._L10
		End Get
		Set
			If (String.Equals(Me._L10, value) = false) Then
				Me._L10 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Email Alias]", Storage:="_Email_Alias", DbType:="VarChar(255)")>  _
	Public Property Email_Alias() As String
		Get
			Return Me._Email_Alias
		End Get
		Set
			If (String.Equals(Me._Email_Alias, value) = false) Then
				Me._Email_Alias = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Job Title]", Storage:="_Job_Title", DbType:="VarChar(255)")>  _
	Public Property Job_Title() As String
		Get
			Return Me._Job_Title
		End Get
		Set
			If (String.Equals(Me._Job_Title, value) = false) Then
				Me._Job_Title = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Country Name]", Storage:="_Country_Name", DbType:="VarChar(50)")>  _
	Public Property Country_Name() As String
		Get
			Return Me._Country_Name
		End Get
		Set
			If (String.Equals(Me._Country_Name, value) = false) Then
				Me._Country_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Manager Name]", Storage:="_Manager_Name", DbType:="VarChar(50)")>  _
	Public Property Manager_Name() As String
		Get
			Return Me._Manager_Name
		End Get
		Set
			If (String.Equals(Me._Manager_Name, value) = false) Then
				Me._Manager_Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Manager Employee ID]", Storage:="_Manager_Employee_ID", DbType:="VarChar(50)")>  _
	Public Property Manager_Employee_ID() As String
		Get
			Return Me._Manager_Employee_ID
		End Get
		Set
			If (String.Equals(Me._Manager_Employee_ID, value) = false) Then
				Me._Manager_Employee_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Manager Email Alias]", Storage:="_Manager_Email_Alias", DbType:="VarChar(255)")>  _
	Public Property Manager_Email_Alias() As String
		Get
			Return Me._Manager_Email_Alias
		End Get
		Set
			If (String.Equals(Me._Manager_Email_Alias, value) = false) Then
				Me._Manager_Email_Alias = value
			End If
		End Set
	End Property
End Class
